"""initial schema

Revision ID: 3fdb0d26f4d9
Revises: 
Create Date: 2026-09-06 14:35:54.911917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdb0d26f4d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_problem', sa.Text(), nullable=False),
    sa.Column('raw_solution', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('normalized_problem', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('why_solution_worked', sa.Text(), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('unresolved', 'investigating', 'solved', 'abandoned', 'obsolete', name='incidentstatus', native_enum=False), server_default='unresolved', nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_ai_review', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_title'), ['title'], unique=False)

    # --- FTS5 lexical index (docs/RESEARCH.md § SQLite & FTS5) ---
    # External-content tables: no duplicated storage, `incidents` stays the sole
    # source of truth. Two tables: prose (tuned tokenchars so identifiers like
    # ECONNREFUSED/NullPointerException stay whole tokens) + trigram (substring
    # search over raw problem/solution text, which often contains pasted logs).
    # Co-located with the `incidents` table definition in this same migration
    # deliberately — see "Trigger DDL must travel with canonical schema changes"
    # in docs/RESEARCH.md.
    op.execute(
        """
        CREATE VIRTUAL TABLE incidents_fts USING fts5(
            title, normalized_problem, symptoms, root_cause, solution, explanation,
            why_solution_worked, lesson_learned, raw_problem, raw_solution,
            content='incidents', content_rowid='id',
            tokenize = "unicode61 remove_diacritics 2 tokenchars '_.-:#/'"
        )
        """
    )
    op.execute(
        """
        CREATE VIRTUAL TABLE incidents_fts_trigram USING fts5(
            raw_problem, raw_solution,
            content='incidents', content_rowid='id',
            tokenize = 'trigram case_sensitive 0'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER incidents_ai AFTER INSERT ON incidents BEGIN
          INSERT INTO incidents_fts(rowid, title, normalized_problem, symptoms, root_cause,
            solution, explanation, why_solution_worked, lesson_learned, raw_problem, raw_solution)
          VALUES (new.id, new.title, new.normalized_problem, new.symptoms, new.root_cause,
            new.solution, new.explanation, new.why_solution_worked, new.lesson_learned,
            new.raw_problem, new.raw_solution);
          INSERT INTO incidents_fts_trigram(rowid, raw_problem, raw_solution)
          VALUES (new.id, new.raw_problem, new.raw_solution);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER incidents_ad AFTER DELETE ON incidents BEGIN
          INSERT INTO incidents_fts(incidents_fts, rowid, title, normalized_problem, symptoms,
            root_cause, solution, explanation, why_solution_worked, lesson_learned, raw_problem,
            raw_solution)
          VALUES('delete', old.id, old.title, old.normalized_problem, old.symptoms, old.root_cause,
            old.solution, old.explanation, old.why_solution_worked, old.lesson_learned,
            old.raw_problem, old.raw_solution);
          INSERT INTO incidents_fts_trigram(incidents_fts_trigram, rowid, raw_problem, raw_solution)
          VALUES('delete', old.id, old.raw_problem, old.raw_solution);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER incidents_au AFTER UPDATE ON incidents BEGIN
          INSERT INTO incidents_fts(incidents_fts, rowid, title, normalized_problem, symptoms,
            root_cause, solution, explanation, why_solution_worked, lesson_learned, raw_problem,
            raw_solution)
          VALUES('delete', old.id, old.title, old.normalized_problem, old.symptoms, old.root_cause,
            old.solution, old.explanation, old.why_solution_worked, old.lesson_learned,
            old.raw_problem, old.raw_solution);
          INSERT INTO incidents_fts(rowid, title, normalized_problem, symptoms, root_cause,
            solution, explanation, why_solution_worked, lesson_learned, raw_problem, raw_solution)
          VALUES (new.id, new.title, new.normalized_problem, new.symptoms, new.root_cause,
            new.solution, new.explanation, new.why_solution_worked, new.lesson_learned,
            new.raw_problem, new.raw_solution);
          INSERT INTO incidents_fts_trigram(incidents_fts_trigram, rowid, raw_problem, raw_solution)
          VALUES('delete', old.id, old.raw_problem, old.raw_solution);
          INSERT INTO incidents_fts_trigram(rowid, raw_problem, raw_solution)
          VALUES (new.id, new.raw_problem, new.raw_solution);
        END
        """
    )

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technologies_name'), ['name'], unique=True)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_sha256'), ['sha256'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('why_failed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_incident_id'), ['incident_id'], unique=False)

    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('chunk_key', sa.String(length=50), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_revision', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunk_embeddings_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_embeddings_model_name'), ['model_name'], unique=False)

    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('operating_system', sa.String(length=200), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('hardware', sa.String(length=200), nullable=True),
    sa.Column('cpu', sa.String(length=200), nullable=True),
    sa.Column('gpu', sa.String(length=200), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('firmware', sa.String(length=200), nullable=True),
    sa.Column('driver_versions', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('runtime', sa.String(length=200), nullable=True),
    sa.Column('compiler', sa.String(length=200), nullable=True),
    sa.Column('framework', sa.String(length=200), nullable=True),
    sa.Column('library', sa.String(length=200), nullable=True),
    sa.Column('library_versions', sa.String(length=1000), nullable=True),
    sa.Column('container', sa.String(length=200), nullable=True),
    sa.Column('configuration', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_incident_id'), ['incident_id'], unique=True)

    op.create_table('extraction_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('basis', sa.Enum('explicit', 'inferred', 'synthesized', 'unknown', name='provenancebasis', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('extractor_provider', sa.String(length=50), nullable=False),
    sa.Column('extractor_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_provenance_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_projects',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'project_id')
    )
    with op.batch_alter_table('incident_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_projects_project_id'), ['project_id'], unique=False)

    op.create_table('incident_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_incident_id', sa.Integer(), nullable=False),
    sa.Column('target_incident_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('related_to', 'caused_by', 'solved_by', 'supersedes', 'duplicate_of', name='incidentrelationtype', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('human', 'ai_extracted', 'ai_suggested', name='attributionsource', native_enum=False), server_default='human', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_incident_id != target_incident_id'),
    sa.ForeignKeyConstraint(['source_incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_incident_id', 'target_incident_id', 'relation_type')
    )
    with op.batch_alter_table('incident_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_relations_source_incident_id'), ['source_incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_relations_target_incident_id'), ['target_incident_id'], unique=False)

    op.create_table('incident_tags',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'tag_id')
    )
    with op.batch_alter_table('incident_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('incident_technologies',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('human', 'ai_extracted', 'ai_suggested', name='attributionsource', native_enum=False), server_default='human', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'technology_id')
    )
    with op.batch_alter_table('incident_technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_technologies_technology_id'), ['technology_id'], unique=False)

    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('user_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_incident_id'), ['incident_id'], unique=False)

    op.create_table('technology_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_technology_id', sa.Integer(), nullable=False),
    sa.Column('target_technology_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('depends_on', 'part_of', 'replaces', 'related_to', name='technologyrelationtype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_technology_id != target_technology_id'),
    sa.ForeignKeyConstraint(['source_technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_technology_id', 'target_technology_id', 'relation_type')
    )
    with op.batch_alter_table('technology_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technology_relations_source_technology_id'), ['source_technology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technology_relations_target_technology_id'), ['target_technology_id'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_incident_id'), ['incident_id'], unique=False)

    op.create_table('extracted_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'partial', 'failed', 'skipped', name='extractionstatus', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extractor_engine', sa.String(length=100), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('source_attachment_hash', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_texts_attachment_id'), ['attachment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_texts_attachment_id'))

    op.drop_table('extracted_texts')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_incident_id'))

    op.drop_table('commands')
    with op.batch_alter_table('technology_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technology_relations_target_technology_id'))
        batch_op.drop_index(batch_op.f('ix_technology_relations_source_technology_id'))

    op.drop_table('technology_relations')
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_incident_id'))

    op.drop_table('revisions')
    with op.batch_alter_table('incident_technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_technologies_technology_id'))

    op.drop_table('incident_technologies')
    with op.batch_alter_table('incident_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_tags_tag_id'))

    op.drop_table('incident_tags')
    with op.batch_alter_table('incident_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_relations_target_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_relations_source_incident_id'))

    op.drop_table('incident_relations')
    with op.batch_alter_table('incident_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_projects_project_id'))

    op.drop_table('incident_projects')
    with op.batch_alter_table('extraction_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_provenance_incident_id'))

    op.drop_table('extraction_provenance')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_incident_id'))

    op.drop_table('environments')
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunk_embeddings_model_name'))
        batch_op.drop_index(batch_op.f('ix_chunk_embeddings_incident_id'))

    op.drop_table('chunk_embeddings')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_incident_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_attachments_incident_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technologies_name'))

    op.drop_table('technologies')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')

    op.execute("DROP TRIGGER IF EXISTS incidents_au")
    op.execute("DROP TRIGGER IF EXISTS incidents_ad")
    op.execute("DROP TRIGGER IF EXISTS incidents_ai")
    op.execute("DROP TABLE IF EXISTS incidents_fts_trigram")
    op.execute("DROP TABLE IF EXISTS incidents_fts")

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_title'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
